#!/bin/sh
UNICHARSET_VERSION="v1"
for f in DangAmbigs freq-dawg.${UNICHARSET_VERSION} inttemp normproto pffmtable
  unicharset.${UNICHARSET_VERSION} user-words word-dawg.${UNICHARSET_VERSION}
do
	if [ ! -r $1.$f ]
	then
		touch $1.$f
	fi
done
