#! /bin/bash

cat $1 |
grep -v "#" |
grep -v "^$" |
cut -f2 |
sort |
uniq -c |
sort -nr |
sed 's/ *[0-9][0-9]* //' > $1.words

cat $1.words | 
head -1000 > $1.words.top.1000

cat $1.words | 
tail -n +1001 > $1.words.1001.to.last

cat $1.words |
egrep "[0-9]" | 
sed 's/[0-9]/ /g' > $1.digit_words

cat $1 |
grep -v "#" |
cut -f2 |
sed 's/[0-9]/ /g' |
./print_word_bigrams.py |
sort |
uniq > $1.word_bigrams
