# GitHub actions - Create Tesseract installer for Windows

name: Cross build for Windows

on:
  # Trigger workflow in GitHub web frontend or from API.
  workflow_dispatch:
    inputs:
      targets:
        description: 'Target operating system'
        required: true
        default: 'Windows (64 bit)'
        type: choice
        options:
          - 'Windows (64 bit)'

jobs:
  build64:
    runs-on: [ubuntu-24.04]
    steps:
    - uses: actions/checkout@v7
    - name: Build Tesseract installer (64 bit)
      run: nsis/build.sh x86_64
    - uses: actions/upload-artifact@v7
      with:
        name: Tesseract Installer for Windows (64 bit)
        path: bin/ndebug/x86_64-w64-mingw32/nsis/tesseract-ocr-w*-setup-*.exe
        archive: false
